src/objects/Candidate_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Candidate Criteria</relationshipLabel>
        <relationshipName>Candidate_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <label>Target Field</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Candidate Criteria</label>
    <nameField>
        <displayFormat>CCN-{0000}</displayFormat>
        <label>Candidate Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equals</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ends with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>does not contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
          
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relationship_Name__c</fullName>
        <label>Relationship Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Criteria</relationshipLabel>
        <relationshipName>Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Criteria_Values__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Values__c</fullName>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Criteria Values</relationshipLabel>
        <relationshipName>Criteria_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>100</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Criteria Value</label>
    <nameField>
        <displayFormat>CV-{0000}</displayFormat>
        <label>Criteria Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criteria Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rule__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Object__c</fullName>
        <label>Candidate Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate_Output_Field__c</fullName>
        <label>Candidate Output Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimum_Score__c</fullName>
        <label>Minimum Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <defaultValue>&quot;Account&quot;</defaultValue>
        <label>Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Output_Field__c</fullName>
        <label>Output Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Output_Value__c</fullName>
        <label>Output Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Score__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Return Score</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Rule.cls
public virtual with sharing class Rule {
    private Double mScore;
    private Rule__c mRule;
    private List<Criteria__c> mCriteria;
    private List<Candidate_Criteria__c> mCandidateCriteria;
    private List<SObject> mCandidates;
  
   
    private static List<Rule> GenerateRulesFromRuleSObjectMap(Map<Id, Rule__c> ruleMap){
        Map<Id, List<Criteria__c>> ruleCriteria = new Map<Id, List<Criteria__c>>();
        Map<Id, List<Candidate_Criteria__c>> ruleCandidateCriteria = new Map<Id, List<Candidate_Criteria__c>>();
        List<Rule> rules = new List<Rule>();
        for (Criteria__c c : [select id, (select value__c, score__c from criteria_values__r), operator__c, rule__c,
                                                                                                    Relationship_Name__c, Field__c, is_required__c
                                                                                                    from Criteria__c
                                                                                                    where Rule__c in :ruleMap.keyset()]) {
            if (ruleCriteria.containsKey(c.rule__c)==false) {
                ruleCriteria.put(c.rule__c, new List<Criteria__c>());
            }
            
            ruleCriteria.get(c.rule__c).add(c);                         
        }
        for (Candidate_Criteria__c cc : [select id,  rule__c, Source_Field__c, Score__c, Target_Field__c, is_required__c
                                                                                                    from Candidate_Criteria__c
                                                                                                    where Rule__c in :ruleMap.keyset()]) {
            if (ruleCandidateCriteria.containsKey(cc.rule__c)==false)   {
                ruleCandidateCriteria.put(cc.rule__c, new List<Candidate_Criteria__c>());
            }

            ruleCandidateCriteria.get(cc.rule__c).add(cc);                          
        }
        
        
        for (Rule__c r : ruleMap.values()){
            rules.add(new Rule(r, ruleCriteria.get(r.id), ruleCandidateCriteria.get(r.id)));
        }
        return rules;       
    }
    public  static Rule GenerateRuleFromSObject(Rule__c ruleRecord) {
        return Rule.GenerateRulesFromRuleSObjectMap(new Map<id,rule__c>{ruleRecord.id=>ruleRecord})[0];
    }
    public static Map<Id, Rule> GenerateRulesAsMap(String sobjType) {
     return GenerateRulesAsMap(Schema.getGlobalDescribe().get(sobjType));
       
    }
    public static Map<Id, Rule> GenerateRulesAsMap(SObjectType sobjType) {
        Map<Id, Rule> rulesMap = new Map<Id, Rule>();
        for (Rule r : GenerateRules(sobjType)) {
            rulesMap.put(r.id, r);
        }
        return rulesMap;
    }
    public static List<Rule> GenerateRules (SObjectType sobjType) {     
        String objName = sobjType.getDescribe().getLocalName();
        Map<Id, Rule__c> ruleMap = new Map<Id, Rule__c>([select id,object__c, name, score__c, OwnerId, output_field__c, output_value__c, return_score__c, Minimum_Score__c, 
                                                candidate_output_field__c, candidate_object__c,
                                                (select  operator__c, Relationship_Name__c,field__c from Criteria__r)
                                                from Rule__c
                                                where Object__c = :objName
                                                order by score__c]);
        return GenerateRulesFromRuleSObjectMap(ruleMap);
    }
    public static List<Rule> GenerateRules(SObjectType sobjType, Set<ID> filterRulesIdList) {
        String objName = sobjType.getDescribe().getLocalName();
        Map<Id, Rule__c> ruleMap = new Map<Id, Rule__c>([select id,object__c, name, score__c, OwnerId, output_field__c, output_value__c, return_score__c, Minimum_Score__c, 
                                                candidate_output_field__c, candidate_object__c,
                                                (select  operator__c, Relationship_Name__c,field__c from Criteria__r)
                                                from Rule__c
                                                where Object__c = :objName and Id in :filterRulesIdList
                                                order by score__c]);
        return GenerateRulesFromRuleSObjectMap(ruleMap);
        
    }

    public Rule(Rule__c rule, List<Criteria__c> criteria,List<Candidate_Criteria__c> candidateCriteria){
            this.mRule = rule;
            this.mCriteria = criteria;
            this.mCandidateCriteria = candidateCriteria;
    }
    
    public String OutputField {
        get { return mRule.output_field__c;}
    }
    public String OutputValue {
        get { return mRule.output_value__c;}
    }
    public String ObjectTypeName {
        get {return mRule.object__c;}
    }
    private string nName;
    public String Name {
        get {
             if (nName == null) {
              nName =  mRule.Name;
             }
             return nName;
        }
    }
    public Id Id {
        get {return mRule.Id;}
    }
    public Double RuleScore {
        get { return mRule.score__c;}
    }
    public Boolean ReturnScore {
        get { return mRule.return_score__c;}
    }
    public String CandidateOutputField {
        get { return mRule.candidate_output_field__c;}
    }   
    public Map<String,List<String>> Fields {
        get {
            Map<String,List<String>> fieldMap = new Map<String,List<String>>();
            fieldMap.put(mRule.object__c, new List<String>());
            for (Criteria__c sc : mRule.Criteria__r) {                  
                if ( sc.relationship_name__c!=null && sc.relationship_name__c!='') {
                    if (fieldMap.containsKey(sc.relationship_name__c)==false) {
                        fieldMap.put(sc.relationship_name__c, new List<String>());
                    }
                    fieldMap.get(sc.relationship_name__c).add(sc.field__c);
                } else if (sc.field__c !=null & sc.field__c != '') {
                    fieldMap.get(mRule.object__c).add(sc.field__c);
                }
            }
            return fieldMap;
        }
    }   
    public List<SObject> Candidates {
        get {
            if (mCandidates==null && CandidateCriteria!=null && CandidateCriteria.IsEmpty()==false) {
                List<SObject>queryResults;
                List<String> restrictList = new List<String>(); //TODO
                SOQLBuilder sb = new SOQLBuilder(mRule.candidate_object__c);
                for (Candidate_Criteria__c c : CandidateCriteria) {
                    sb.addField(c.Target_Field__c);     
                }
        
                if (restrictList != null){
                    String restrict='';
                    for (String candidateId : restrictList) {
                        restrict += (restrict != '' ? ', ' : '') + candidateId; 
                    }
                    if (restrict!='') {
                          sb.addCriteria('id in (' + restrict + ')', true);
                    }
                }

                
                mCandidates = Database.query(sb.getSOQL());         
            }
            return mCandidates;
        }
    }       
    public List<Candidate_Criteria__c> CandidateCriteria {
        get {
            return mCandidateCriteria;
        }
    }
    public List<Criteria__c> RuleCriteria {
        get {
            return mCriteria;
        }
    }
 
    private Double scoreCriteria(SObject targetRecord, Criteria__c critieria){
        Double score = 0;
        Operator op = OperatorBuilder.getOperator(critieria.operator__c);
        for (Criteria_Values__c cv : critieria.criteria_values__r){
                if (cv.score__c != null){
                score += op.interpret( targetRecord.get(critieria.Field__c), cv.value__c) ? cv.score__c : 0;
                }
        }
        return score;
    }
    private Double scoreCandidateCriteria(SObject candidateRecord, SObject targetRecord, Candidate_Criteria__c critieria){
        Double score = 0;
        Operator op = new EqualsOperator();
        score = op.interpret( targetRecord.get(critieria.Source_Field__c), 
                        candidateRecord.get(critieria.Target_Field__c)) ? critieria.score__c : 0;
        return score;
    }
            
    public RuleProcessingResult executeRule(SObject targetRecord) {
        return executeRule(targetRecord, targetRecord);
    }   
    public RuleProcessingResult executeRule(SObject targetRecord, SObject relatedRecords){
        RuleProcessingResult result = new RuleProcessingResult(Candidates);
        Long failedRequiredCriteria = 0;
        // generate rule score <--- this score is used when comparing to other rules to determine which one wins
        if (RuleCriteria !=null) {
            for (Criteria__c c : RuleCriteria){
                Double score = 0;
    
                if (c.relationship_name__c == '' || c.relationship_name__c == null ) {
                    score = scoreCriteria(targetRecord, c);
                } else if ( relatedRecords.getSObjects(c.relationship_name__c) != null && relatedRecords.getSObjects(c.relationship_name__c).IsEmpty()==false){
                    //it is looking at the related records so loop through all of them and score them individually              
                    for (Sobject o : relatedRecords.getSObjects(c.relationship_name__c)) {
                        score += scoreCriteria(o, c);
                    }
                }
                result.score += score;
                failedRequiredCriteria += (c.is_Required__c && score <= 0) ? 1 : 0;
            }
        }
        result.hasPassed = (failedRequiredCriteria == 0 && (mRule.minimum_score__c ==null || result.score > mRule.minimum_score__c));
        
        // score the individual Candidates <---- this score is used to determine which candidate is the "best" for this rule
        if (CandidateCriteria != null && CandidateCriteria.IsEmpty()==false) {
            for (Candidate candidate : result.candidates) {
                for (Candidate_Criteria__c c : CandidateCriteria) {
                    candidate.score+=scoreCandidateCriteria(candidate.record, targetRecord, c);
                }
            }
        }
        System.Debug('Rule results for  ' + this.Name  + ' is ' + result);

        
        return result;
    }
        
    public class RuleProcessingResult {
        private Candidate mWinningCandidate;
        public boolean hasPassed = false;
        public double  score = 0;
        public List<Candidate> candidates;
        
        public RuleProcessingResult(List<SObject> candidates) {
            this.candidates = new List<Candidate>();
            if (candidates !=null && candidates.IsEmpty()==false) {
                for (SObject c : candidates) {
                    this.candidates.add(new Candidate(c));
                }
            }
        }
        
        public Candidate winningCandidate{
            get {
                if (mWinningCandidate == null && candidates !=null && candidates.IsEmpty()==false) {
                    for (Candidate c : candidates){
                        if (mWinningCandidate==null || c.Score > mWinningCandidate.Score) {
                            mWinningCandidate = c;
                        }
                    }
                }
                return mWinningCandidate;
            }
        }
    }
    public class Candidate {
        public SObject record;
        public double score = 0;
        public Candidate (SObject record){
            this.record = record;
        }
    }
    
   
}