src/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equals</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ends with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>does not contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
          
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relationship_Name__c</fullName>
        <label>Relationship Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Criteria_Values__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Values__c</fullName>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Criteria Values</relationshipLabel>
        <relationshipName>Criteria_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Criteria Value</label>
    <nameField>
        <displayFormat>CV-{0000}</displayFormat>
        <label>Criteria Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criteria Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RuleSOQLBuilder.cls
public  with sharing class RuleSOQLBuilder extends SOQLBuilder {
    private Rule rule;
    public RuleSOQLBuilder (Rule rule) {
        super(rule.ObjectTypeName);
        this.rule = rule;
        addFieldsFromRule(rule);
    }
    
    public RuleSOQLBuilder (List<Rule> rules) {
        super(rules[0].ObjectTypeName);
        for (Rule r : rules) {
            addFieldsFromRule(r);
        }
    }
    
    private void addFieldsFromRule(Rule rule) {
     for (String s : rule.fields.keyset()) {
            if (s == rule.ObjectTypeName) {
                this.addFields(rule.fields.get(s));
            } else {
                this.addFields(s, rule.fields.get(s));
            }
        }
    }
    
    public void addRuleCriteria() {
        if (rule.RuleCriteria!=null) {
            for (Criteria__c c:rule.RuleCriteria){
                string operator = c.operator__c;
                string condition;
                string field = c.field__c;
             /*   if (c.relationship_name__c!=''  && c.relationship_name__c!=null) {
                    field = c.relationship_name__c + '.' + field;
                }*/

                for (Criteria_Values__c cv : c.Criteria_Values__r) {
                    System.Debug('add rule criteria value');
               
                    object targetValue = cv.value__c;
                    Operator op = OperatorBuilder.getOperator(c.operator__c);
                    if (c.relationship_name__c!=''  && c.relationship_name__c!=null) {
                        addCriteria(c.relationship_name__c, op.getSoqlCriteria(field,targetValue),true);
                    } else {
                        addCriteria(op.getSoqlCriteria(field,targetValue),true);
                    }
                 }
            }
        }
    }
 }